name: mad_mom_mag
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^3.1.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  dio: ^5.3.2
  image_picker: ^1.0.1
  zoom_tap_animation: ^1.1.0
  equatable: ^2.0.5
  lottie: ^2.6.0
  url_launcher: ^6.1.12
  mask_text_input_formatter:
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

